export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"
export const SIGN_UP = "SIGN_UP"

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_DETAIL_PRODUCT = "GET_DETAIL_PRODUCT"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const GET_CART_ITEMS = "GET_CART_ITEMS"
export const CHANGE_CART_ITEM_COUNT = "CHANGE_CART_ITEM_COUNT"
export const ADD_TO_CART_FROM_DETAIL = "ADD_TO_CART_FROM_DETAIL"